# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/e/学校课程/程序设计/大作业2/main

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/e/学校课程/程序设计/大作业2/main

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/e/学校课程/程序设计/大作业2/main/CMakeFiles /mnt/e/学校课程/程序设计/大作业2/main//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/e/学校课程/程序设计/大作业2/main/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named car

# Build rule for target.
car: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 car
.PHONY : car

# fast build rule for target.
car/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/car.dir/build.make CMakeFiles/car.dir/build
.PHONY : car/fast

hc_sr04.o: hc_sr04.cpp.o
.PHONY : hc_sr04.o

# target to build an object file
hc_sr04.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/car.dir/build.make CMakeFiles/car.dir/hc_sr04.cpp.o
.PHONY : hc_sr04.cpp.o

hc_sr04.i: hc_sr04.cpp.i
.PHONY : hc_sr04.i

# target to preprocess a source file
hc_sr04.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/car.dir/build.make CMakeFiles/car.dir/hc_sr04.cpp.i
.PHONY : hc_sr04.cpp.i

hc_sr04.s: hc_sr04.cpp.s
.PHONY : hc_sr04.s

# target to generate assembly for a file
hc_sr04.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/car.dir/build.make CMakeFiles/car.dir/hc_sr04.cpp.s
.PHONY : hc_sr04.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/car.dir/build.make CMakeFiles/car.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/car.dir/build.make CMakeFiles/car.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/car.dir/build.make CMakeFiles/car.dir/main.cpp.s
.PHONY : main.cpp.s

motor.o: motor.cpp.o
.PHONY : motor.o

# target to build an object file
motor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/car.dir/build.make CMakeFiles/car.dir/motor.cpp.o
.PHONY : motor.cpp.o

motor.i: motor.cpp.i
.PHONY : motor.i

# target to preprocess a source file
motor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/car.dir/build.make CMakeFiles/car.dir/motor.cpp.i
.PHONY : motor.cpp.i

motor.s: motor.cpp.s
.PHONY : motor.s

# target to generate assembly for a file
motor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/car.dir/build.make CMakeFiles/car.dir/motor.cpp.s
.PHONY : motor.cpp.s

track_sensor.o: track_sensor.cpp.o
.PHONY : track_sensor.o

# target to build an object file
track_sensor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/car.dir/build.make CMakeFiles/car.dir/track_sensor.cpp.o
.PHONY : track_sensor.cpp.o

track_sensor.i: track_sensor.cpp.i
.PHONY : track_sensor.i

# target to preprocess a source file
track_sensor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/car.dir/build.make CMakeFiles/car.dir/track_sensor.cpp.i
.PHONY : track_sensor.cpp.i

track_sensor.s: track_sensor.cpp.s
.PHONY : track_sensor.s

# target to generate assembly for a file
track_sensor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/car.dir/build.make CMakeFiles/car.dir/track_sensor.cpp.s
.PHONY : track_sensor.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... car"
	@echo "... hc_sr04.o"
	@echo "... hc_sr04.i"
	@echo "... hc_sr04.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... motor.o"
	@echo "... motor.i"
	@echo "... motor.s"
	@echo "... track_sensor.o"
	@echo "... track_sensor.i"
	@echo "... track_sensor.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

